name: cntlm-ondra
version: "0.92.3"
summary: cntlm proxy authenticator
description: |
 cntlm proxy authenticator

confinement: strict
grade: stable
base: core18

apps:

    cntlm:
        command: etc/init.d/cntlm start
        stop-command: etc/init.d/cntlm stop
        plugs: [network, network-bind]
        daemon: simple

    start:
        command: etc/init.d/cntlm start
        plugs: [network, network-bind]

    restart:
        command: etc/init.d/cntlm restart
        plugs: [network, network-bind]

    status:
        command: etc/init.d/cntlm status

    stop:
        command: etc/init.d/cntlm stop

parts:
    proxy:
        plugin: nil
        stage-packages:
          - cntlm
          - dpkg
        install: |
            sed -i 's|PATH=|PATH=$PATH:|g' $SNAPCRAFT_PART_INSTALL/etc/init.d/cntlm
            sed -i 's|DAEMON=|DAEMON=$SNAP|g' $SNAPCRAFT_PART_INSTALL/etc/init.d/cntlm
            sed -i 's|PIDFILE=/var/run/cntlm|PIDFILE=$SNAP_DATA/run|g' $SNAPCRAFT_PART_INSTALL/etc/init.d/cntlm
            sed -i 's|/etc/default/rcS|$SNAP_COMMON/etc/default/rcS|g' $SNAPCRAFT_PART_INSTALL/etc/init.d/cntlm
            sed -i 's|/etc/default/cntlm|$SNAP_COMMON/etc/default/cntlm|g' $SNAPCRAFT_PART_INSTALL/etc/init.d/cntlm
            sed -i '/DAEMON_OPTS="$DAEMON_OPTS/a DAEMON_OPTS="$DAEMON_OPTS -v -c $SNAP_COMMON/etc/cntlm.conf"' $SNAPCRAFT_PART_INSTALL/etc/init.d/cntlm
        prime:
            - -usr/bin/dpkg*
            - -usr/share
            - -var
